#ifndef CONSTANTS_H
#define CONSTANTS_H

// NOTE: need to work on this later.
// to change the size more.
#define IMAGE_SCALE_RATIO (2)
#define XBOX_IMAGE_WIDTH  (1452)
#define XBOX_IMAGE_HEIGHT (940)
#define XBOX_JOYSTICK_SZ  (169)

#define MAX_JOYSTICK_DISPLACEMENT_PX (80)
#define MAX_TRIGGER_DISPLACEMENT_PX (25)

#define SCALED_MAX_JOYSTICK_DISPLACEMENT_PX (MAX_JOYSTICK_DISPLACEMENT_PX / IMAGE_SCALE_RATIO)
#define SCALED_MAX_TRIGGER_DISPLACEMENT_PX  (MAX_TRIGGER_DISPLACEMENT_PX / IMAGE_SCALE_RATIO)

#define SCALED_JOYSTICK_SZ                  (XBOX_JOYSTICK_SZ / IMAGE_SCALE_RATIO)
#define SCALED_WINDOW_WIDTH                 (XBOX_IMAGE_WIDTH / IMAGE_SCALE_RATIO)
#define SCALED_WINDOW_HEIGHT                (XBOX_IMAGE_HEIGHT / IMAGE_SCALE_RATIO)

// This color is unlikely to ever be naturally selected...
#define CHROMA_KEY_COLOR  (RGB(255, 255, 254))

#endif
