#ifndef PLAYSTATION_CONTROLLER_ASSET_ID_H
#define PLAYSTATION_CONTROLLER_ASSET_ID_H

enum PlaystationControllerAssetId { // TODO: unused.
    PLAYSTATIONCONTROLLER_ASSET_BASE = 0,
    PLAYSTATIONCONTROLLER_ASSET_BASE_FILL,
    PLAYSTATIONCONTROLLER_ASSET_BUTTON_CROSS_FILL,
    PLAYSTATIONCONTROLLER_ASSET_BUTTON_CIRCLE_FILL,
    PLAYSTATIONCONTROLLER_ASSET_BUTTON_SQUARE_FILL,
    PLAYSTATIONCONTROLLER_ASSET_BUTTON_TRIANGLE_FILL,
    PLAYSTATIONCONTROLLER_ASSET_DPAD_UP_FILL,
    PLAYSTATIONCONTROLLER_ASSET_DPAD_DOWN_FILL,
    PLAYSTATIONCONTROLLER_ASSET_DPAD_LEFT_FILL,
    PLAYSTATIONCONTROLLER_ASSET_DPAD_RIGHT_FILL,
    PLAYSTATIONCONTROLLER_ASSET_BUTTON_MENU_FILL,
    PLAYSTATIONCONTROLLER_ASSET_BUTTON_START_FILL,
    PLAYSTATIONCONTROLLER_ASSET_RB_FILL,
    PLAYSTATIONCONTROLLER_ASSET_LB_FILL,
    PLAYSTATIONCONTROLLER_ASSET_JOYSTICK,
    PLAYSTATIONCONTROLLER_ASSET_JOYSTICK_FILL,
    PLAYSTATIONCONTROLLER_ASSET_RT,
    PLAYSTATIONCONTROLLER_ASSET_RT_FILL,
    PLAYSTATIONCONTROLLER_ASSET_LT,
    PLAYSTATIONCONTROLLER_ASSET_LT_FILL,
    PLAYSTATIONCONTROLLER_ASSET_COUNT,
};

#endif
