#ifndef XBOX_CONTROLLER_ASSET_ID_H
#define XBOX_CONTROLLER_ASSET_ID_H

enum XboxControllerAssetId {
    XBOXCONTROLLER_ASSET_BASE = 0,
    XBOXCONTROLLER_ASSET_BASE_FILL,
    XBOXCONTROLLER_ASSET_BUTTON_A_FILL,
    XBOXCONTROLLER_ASSET_BUTTON_B_FILL,
    XBOXCONTROLLER_ASSET_BUTTON_X_FILL,
    XBOXCONTROLLER_ASSET_BUTTON_Y_FILL,
    XBOXCONTROLLER_ASSET_DPAD_UP_FILL,
    XBOXCONTROLLER_ASSET_DPAD_DOWN_FILL,
    XBOXCONTROLLER_ASSET_DPAD_LEFT_FILL,
    XBOXCONTROLLER_ASSET_DPAD_RIGHT_FILL,
    XBOXCONTROLLER_ASSET_BUTTON_MENU_FILL,
    XBOXCONTROLLER_ASSET_BUTTON_START_FILL,
    XBOXCONTROLLER_ASSET_RB_FILL,
    XBOXCONTROLLER_ASSET_LB_FILL,
    XBOXCONTROLLER_ASSET_JOYSTICK,
    XBOXCONTROLLER_ASSET_JOYSTICK_FILL,
    XBOXCONTROLLER_ASSET_RT,
    XBOXCONTROLLER_ASSET_RT_FILL,
    XBOXCONTROLLER_ASSET_LT,
    XBOXCONTROLLER_ASSET_LT_FILL,

    XBOXCONTROLLER_ASSET_COUNT,
};

#endif
