#ifndef KEYBOARD_ASSET_ID_H
#define KEYBOARD_ASSET_ID_H

// TODO:

// NOTE: the image I use by default is just based on an Apple Magic Keyboard.
enum KeyboardAssetSet {
    KEYBOARD_ASSET_SET_ALPHANUMERIC,
    KEYBOARD_ASSET_SET_TENKEYLESS,
    KEYBOARD_ASSET_SET_FULLSIZE,
};

// an asset per key.
enum KeyboardAssetId {
    // ALPHANUMERIC

    KEYBOARD_ASSET_F1,
    KEYBOARD_ASSET_F2,
    KEYBOARD_ASSET_F3,
    KEYBOARD_ASSET_F4,
    KEYBOARD_ASSET_F5,
    KEYBOARD_ASSET_F6,
    KEYBOARD_ASSET_F7,
    KEYBOARD_ASSET_F8,
    KEYBOARD_ASSET_F9,
    KEYBOARD_ASSET_F10,
    KEYBOARD_ASSET_F11,
    KEYBOARD_ASSET_F12,

    // TENKEYLESS

    // FULLSIZE
};

#endif
