#ifndef KEYBOARD_PUPPET_POINT_IDS_H
#define KEYBOARD_PUPPET_POINT_IDS_H

enum KeyboardPuppetPointId {
    KEYBOARD_PUPPET_POINT_KEY_F1,
    KEYBOARD_PUPPET_POINT_KEY_F2,
    KEYBOARD_PUPPET_POINT_KEY_F3,
    KEYBOARD_PUPPET_POINT_KEY_F4,
    KEYBOARD_PUPPET_POINT_KEY_F5,
    KEYBOARD_PUPPET_POINT_KEY_F6,
    KEYBOARD_PUPPET_POINT_KEY_F7,
    KEYBOARD_PUPPET_POINT_KEY_F8,
    KEYBOARD_PUPPET_POINT_KEY_F9,
    KEYBOARD_PUPPET_POINT_KEY_F10,
    KEYBOARD_PUPPET_POINT_KEY_F11,
    KEYBOARD_PUPPET_POINT_KEY_F12,

    // TODO;
    KEYBOARD_PUPPET_POINT_COUNT,
};

#endif
