#ifndef KEYBOARD_ASSET_ID_H
#define KEYBOARD_ASSET_ID_H

// an asset per key.
enum KeyboardAssetId {
    KEYBOARD_ASSET_BASE,

    // ALPHANUMERIC

    KEYBOARD_ASSET_F1,
    KEYBOARD_ASSET_F2,
    KEYBOARD_ASSET_F3,
    KEYBOARD_ASSET_F4,
    KEYBOARD_ASSET_F5,
    KEYBOARD_ASSET_F6,
    KEYBOARD_ASSET_F7,
    KEYBOARD_ASSET_F8,
    KEYBOARD_ASSET_F9,
    KEYBOARD_ASSET_F10,
    KEYBOARD_ASSET_F11,
    KEYBOARD_ASSET_F12,

    // TENKEYLESS

    // FULLSIZE

    KEYBOARD_ASSET_COUNT
};

#endif
