#ifndef MOUSE_ASSET_ID_H
#define MOUSE_ASSET_ID_H

enum MouseAssetId {
    MOUSE_ASSET_BASE,

    MOUSE_ASSET_BASE_FILL,
    MOUSE_ASSET_LEFT_FILL,
    MOUSE_ASSET_MIDDLE_FILL,
    MOUSE_ASSET_RIGHT_FILL,

    MOUSE_ASSET_COUNT,
};

#endif
