#ifndef MOUSE_PUPPET_POINT_IDS_H
#define MOUSE_PUPPET_POINT_IDS_H

enum MousePuppetPointId {
    MOUSE_PUPPET_POINT_LEFT,
    MOUSE_PUPPET_POINT_MIDDLE,
    MOUSE_PUPPET_POINT_RIGHT,
    MOUSE_PUPPET_POINT_COUNT,
};

#endif
